apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-back
  template:
    metadata:
      labels:
        app: app-back
    spec:
      containers:
      - name: app-back
        image: susguzman/full-back:0.1.0
        env:
        - name: SERVER_PORT
          value: "8500"
        - name: ORACLE_USER
          value: "APPUSER"
        - name: ORACLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: app-pass
        - name: ORACLE_CONNSTR
          value: "service-oracle:1521/xepdb1"  
        - name: AUTH_TOKEN
          value: "tokenbackend"  
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: service-back
spec:
  type: LoadBalancer
  selector:
    app: app-back
  ports:
  - port: 8500
    targetPort: 8500