apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-oracle-pv-claim
  labels:
    app: db-oracle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-oracle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-oracle
  template:
    metadata:
      labels:
        app: db-oracle
    spec:
      securityContext:
        runAsUser: 54321    # Oracle User 
        runAsGroup: 54321   # Oinstall group
        fsGroup: 54321      # Oinstall group
      volumes:
      - name: db-init-volume
        configMap:
          name: db-init-cm
      - name: db-oracle-persistent-storage
        persistentVolumeClaim:
          claimName: db-oracle-pv-claim
      containers:
      - name: db-oracle
        image: gvenzl/oracle-xe
        env:
        - name: ORACLE_PASSWORD   # SYS Pass
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: sys-pass
        - name: APP_USER
          value: "APPUSER"
        - name: APP_USER_PASSWORD # APP Pass
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: app-pass
        resources:
          limits:
            memory: "3000Mi"
            cpu: "1000m"
        ports:
        - containerPort: 1521
        volumeMounts:
        - name: db-init-volume
          mountPath: /container-entrypoint-initdb.d
        - name: db-oracle-persistent-storage
          mountPath: /opt/oracle/oradata
---
apiVersion: v1
kind: Service
metadata:
  name: service-oracle
spec:
  type: ClusterIP
  selector:
    app: db-oracle
  ports:
  - port: 1521
    targetPort: 1521