apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-front
  template:
    metadata:
      labels:
        app: app-front
    spec:
      containers:
      - name: app-front
        image: vitamatias/full-front:0.1.0-nginx-alpine-gcp
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-front
spec:
  type: LoadBalancer
  selector:
    app: app-front
  ports:
  - port: 8888
    targetPort: 80