ALTER SESSION SET CONTAINER = XEPDB1;


-- PERSON CREATION
CREATE TABLE APPUSER.PERSON (
	PERSON NUMBER,
    FIRST_NAME VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(100) UNIQUE NOT NULL,
	PASSWORD VARCHAR2(1000) NOT NULL,
	ADD_DATE DATE DEFAULT SYSDATE,
	PRIMARY KEY(PERSON)
);

-- PERSON SEQUENCE
CREATE SEQUENCE APPUSER.SQ_PERSON NOCACHE;

--ACCOUNT CREATION
CREATE TABLE APPUSER.ACCOUNT (
    ACCOUNT NUMBER NOT NULL,
    BANK VARCHAR2(100) NOT NULL,
    NUMBER_ACCOUNT VARCHAR2(100) NOT NULL,
    TYPE_ACCOUNT VARCHAR2(100) NOT NULL,
    CURRENCY VARCHAR2(100) NOT NULL,
    BALANCE NUMBER NOT NULL,
    PERSON NUMBER NOT NULL,
    ADD_DATE DATE DEFAULT SYSDATE,
    PRIMARY KEY (ACCOUNT),
    FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON)
);
--ACCOUNT SEQUENCE
CREATE SEQUENCE APPUSER.SQ_ACCOUNT NOCACHE;

-- CATEGORY CREATION
CREATE TABLE APPUSER.CATEGORY (
    CATEGORY NUMBER NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    TYPE VARCHAR2(100) NOT NULL,
    PERSON NUMBER NOT NULL,
    ADD_DATE DATE DEFAULT SYSDATE,
    PRIMARY KEY (CATEGORY),
    FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON)
);
--ACCOUNT SEQUENCE
CREATE SEQUENCE APPUSER.SQ_CATEGORY NOCACHE;

--RECORD CREATION
CREATE TABLE APPUSER.RECORD (
    RECORD NUMBER NOT NULL,
    CATEGORY VARCHAR2(100) NOT NULL,
    TYPE VARCHAR2(100) NOT NULL,
    ACCOUNT NUMBER NOT NULL,
    DATES VARCHAR2(15),
    TOTAL NUMBER NOT NULL,
    BALANCE NUMBER NOT NULL,
    OBSERVATION VARCHAR2(100),
    PERSON NUMBER NOT NULL,
    PRIMARY KEY (RECORD),
    FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON),
    FOREIGN KEY(ACCOUNT) REFERENCES APPUSER.ACCOUNT(ACCOUNT)
);
--ACCOUNT SEQUENCE
CREATE SEQUENCE APPUSER.SQ_RECORD NOCACHE;

--RECORD CREATION
CREATE TABLE APPUSER.TRANSFER (
    TRANSFER NUMBER NOT NULL,
    DEBIT_ACCOUNT NUMBER NOT NULL,
    CREDIT_ACCOUNT NUMBER NOT NULL, 
    DESCRIPTION VARCHAR2(100),
    TOTAL NUMBER NOT NULL,
    DATE_TRANSFER VARCHAR2(200) NOT NULL,
    PERSON NUMBER NOT NULL,
    PRIMARY KEY (TRANSFER),
    FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON),
    FOREIGN KEY(DEBIT_ACCOUNT) REFERENCES APPUSER.ACCOUNT(ACCOUNT),
    FOREIGN KEY(CREDIT_ACCOUNT) REFERENCES APPUSER.ACCOUNT(ACCOUNT)
);
--ACCOUNT SEQUENCE
CREATE SEQUENCE APPUSER.SQ_TRANSFER NOCACHE;